### ISSUE TITLE
environment update on master fails when cloning pallets/click

### ISSUE THREAD

**Issue by LGro** [C3S/c3s.ado.repertoire#1]
Following the [README](https://github.com/C3S/collecting_society_docker/blob/develop/README.rst), when I reach running `./update` on the master branch, the script fails on me with:
```
~/Workspace/collecting_society_docker$ ./update 
=====================================================================
  This is the c3s.ado.repertoire update script.
  It will get or update some relevant repositories.

  Using c3s.ado.repertoire on branch b'master\n'
  Installing/updating in /home/LGro/Workspace/collecting_society_docker
  Reading info from config...
  Checking repositories...
------------------------------------------------------------

git pull "collecting_society_docker": b'Already up-to-date.\n'

REPO: click
--------------------------------------------------------------
Will use git to clone "https://github.com/pallets/click.git" tag "4.0" into "ado/ref/click": 
Directory exists; using pull instead of clone:
git checkout "click": Traceback (most recent call last):
  File "./update", line 67, in <module>
    stderr=subprocess.STDOUT)
  File "/home/LGro/anaconda3/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/home/LGro/anaconda3/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '('git', 'clone', '--branch', '4.0', 'https://github.com/pallets/click.git', '/home/LGro/Workspace/collecting_society_docker/ado/ref/click')' returned non-zero exit status 128.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./update", line 97, in <module>
    x for x in checkout_result.strip().split('\n')))
TypeError: a bytes-like object is required, not 'str'
```
Might there be a specific Python version or other dependencies required to run this?

**Comment by thomiel** [comment]
Yes, still Python 2.7. We are currently in the process of switching to Python3/Tryton5. I recommend the develop branch. There are some fixes of bugs coming from the refactoring.

**Comment by LGro** [comment]
Good hint, thanks!
When I create an anaconda environment with Python2.7, many of the repos are successfully cloned, until the following repo fails:
```
REPO: echoprint-codegen
--------------------------------------------------------------
Will use git to clone "https://github.com/spotify/echoprint-codegen.git" branch "master" into "ado/src/echoprint-codegen": 
git clone "echoprint-codegen": 
Cloning into '/home/LGro/Workspace/collecting_society_docker/ado/src/echoprint-codegen'...
copy file ado/etc/trytonpassfile.example to ado/etc/trytonpassfile
copy file tryton.env.example to tryton.env
copy file portal.env.example to portal.env
copy file api.env.example to api.env
copy file processing.env.example to processing.env
copy file selenium.env.example to selenium.env
copy file ado/src/c3sRepertoireProcessing/config.ini.EXAMPLE to ado/src/c3sRepertoireProcessing/config.ini
Traceback (most recent call last):
  File "./update", line 123, in <module>
    shutil.copyfile(source, target)
  File "/home/LGro/anaconda3/envs/c3s_docker/lib/python2.7/shutil.py", line 96, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/home/LGro/Workspace/collecting_society_docker/ado/src/c3sRepertoireProcessing/config.ini.EXAMPLE'
```

Are you interested in fixing the documentation for the current `master` or would you rather add a note in a hotfix that people shouldn't use master?

EDIT: I'm just asking to make sure that I don't bother you with questions that aren't relevant if e.g. develop will be merged into master soon. After all, I'm just curious and don't rely on being able to set this up.

**Comment by thomiel** [comment]
c3sRepertoireProcessing was the old name of the collecting_society_worker. This is a remnant that's left over from the old repo naming structure. We hope to have a clean develop version soon and then sync it with master, including the docs. But you are not bothering at all. May I ask what brought you here?

**Comment by LGro** [comment]
I remembered the C3S activities from a couple years back, went to check how this is going, wanted to write an encouraging email to the team to reflect my appreciation, stumbled across the [contributions page](https://www.c3s.cc/mitentwickeln/), which looked very inviting, and wanted to try out some of the software you're building to see what it's about and if I can contribute.

Thanks for the kind interaction, I'll close this issue as won't fix.
